# Generated by Django 4.0.4 on 2022-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_viaje', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('tipo_de_documento', models.IntegerField()),
                ('numero_de_documento', models.BigIntegerField()),
                ('tipo_de_persona', models.IntegerField()),
                ('rh', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
