# Generated by Django 4.0.4 on 2022-06-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='numero_de_documento',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rh',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefono',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_de_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_de_persona',
            field=models.IntegerField(),
        ),
    ]
