# Generated by Django 4.0.4 on 2022-06-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_correo_alter_usuarios_edad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
