# Generated by Django 4.0.4 on 2022-06-02 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
