# Generated by Django 4.0.4 on 2022-06-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_ciudades_horario_tarifas_vehiculos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('tipo_de_documento', models.IntegerField()),
                ('numero_de_documento', models.BigIntegerField()),
                ('tipo_de_persona', models.IntegerField(default=1)),
                ('rh', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
